name: React CI

on: 
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  build: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14.2] 

    steps:   
      - uses: actions/checkout@v3  
      - run: npm install
      - run: npm run build
      

