---
name: Node.js CI

on: 
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  build: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: '>=16.4.2' 

    steps:   
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run build
      - run: npm test

lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
          

      # CD section
      # - uses: aws-actions/configure-aws-credentials # TODO: needs @v, (version number)
      #   with:
      #     args: --acl public-read --follow-symlinks --deleted
      #   env:
      #     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: 'us-west-2'  # optional: defaults to us-east-1
      #     SOURCE_DIR: 'public'     # optional: defaults to entire repository
      # - uses: actions/checkout@v3  
      # - run: npm install
      # - run: npm run build
      # - uses: actions/checkout@v3  
      # - run: npm install
      # - run: npm run build

      

