---
name: Node.js CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build: 
    runs-on: ubuntu-latest
        strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm run lint

      # name: Deploy to S3
      # CD section
      # - uses: aws-actions/configure-aws-credentials # TODO: needs @v, (version number)
      #   with:
      #     args: --acl public-read --follow-symlinks --deleted
      #   env:
      #     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: 'us-west-2'  # optional: defaults to us-east-1
      #     SOURCE_DIR: 'public'     # optional: defaults to entire repository
      # - uses: actions/checkout@v3  
      # - run: npm install
      # - run: npm run build
      # - uses: actions/checkout@v3  
      # - run: npm install
      # - run: npm run build

      

